
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gec;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 9;
  public static final int CHUNK = 12;
  public static final int LT = 30;
  public static final int RBRACE = 26;
  public static final int RPAREN = 24;
  public static final int DEFINE = 2;
  public static final int INT = 15;
  public static final int LIST = 14;
  public static final int SETUP = 3;
  public static final int IN = 11;
  public static final int WORLD = 4;
  public static final int OP_ARIT = 22;
  public static final int GAMEOBJECT = 13;
  public static final int GT = 31;
  public static final int LBRACE = 25;
  public static final int LPAREN = 23;
  public static final int ID = 18;
  public static final int SCENE = 7;
  public static final int STRING_LITERAL = 21;
  public static final int INT_LITERAL = 19;
  public static final int STRING = 17;
  public static final int COMMA = 29;
  public static final int FLOAT = 16;
  public static final int EOF = 0;
  public static final int ADD = 5;
  public static final int LSQUARE = 27;
  public static final int error = 1;
  public static final int ASSIGN = 32;
  public static final int RSQUARE = 28;
  public static final int APPEND = 6;
  public static final int FLOAT_LITERAL = 20;
  public static final int FOR = 8;
  public static final int TO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINE",
  "SETUP",
  "WORLD",
  "ADD",
  "APPEND",
  "SCENE",
  "FOR",
  "FROM",
  "TO",
  "IN",
  "CHUNK",
  "GAMEOBJECT",
  "LIST",
  "INT",
  "FLOAT",
  "STRING",
  "ID",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "OP_ARIT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LSQUARE",
  "RSQUARE",
  "COMMA",
  "LT",
  "GT",
  "ASSIGN"
  };
}

